# 2次元CNN

In [1]:
import numpy as np

In [37]:
w = np.array([
            [[[1,2],
              [3,4]]],
             [[[1,2],
               [3,4]]]
])
              
test1 = np.array([
                 [[[0, 1, 0], 
                   [0, 1, 0],
                   [0, 1, 0]],
                 [[0, 1, 0], 
                   [0, 1, 0],
                   [0, 1, 0]]],
                 [[[0, 2, 0], 
                   [0, 2, 0],
                   [0, 2, 0]],
                 [[0, 2, 0], 
                   [0, 2, 0],
                   [0, 2, 0]]]
])

In [39]:
test0 = np.array([
                 [[[0, 1, 0], 
                   [0, 1, 0],
                   [0, 1, 0]]],
                 [[[0, 2, 0], 
                   [0, 2, 0],
                   [0, 2, 0]]]
])

In [20]:
test1[0,0:2,0:2,0:2]

array([[[0, 1],
        [0, 1]]])

In [23]:
test1[0,0:1,0:2,0:2]

array([[[0, 1],
        [0, 1]]])

In [34]:
w[0]

array([[[1, 2],
        [3, 4]]])

In [43]:
test2 = np.empty((2,1,2,2))
for sample in range(2):
    for row in range(2):
        for col in range(2):
            test2[sample, 0, row, col] = np.sum(test1[sample, :, row:row+2, col:col+2] * w[sample])
test2

array([[[[12.,  8.],
         [12.,  8.]]],


       [[[24., 16.],
         [24., 16.]]]])

In [45]:
test1[0, :, 0:2, 0:2] * w[0]

array([[[0, 2],
        [0, 4]],

       [[0, 2],
        [0, 4]]])

In [40]:
test2 = np.empty((2,1,2,2))
n_sample = 2

for sample in range(n_sample):
    for row in range(2):
        for col in range(2):
            test2[sample, 0, row, col] = np.sum(test0[sample, 0:1, row:row+2, col:col+2] * w[sample])
test2

array([[[[ 6.,  4.],
         [ 6.,  4.]]],


       [[[12.,  8.],
         [12.,  8.]]]])